"use client";

import { useCallback, useLayoutEffect, useState } from "react";

export type Language = "km" | "en";

const STORAGE_KEY = "findroom.language";
const EVENT = "findroom:language-change";

function readStored(): Language {
  if (typeof window === "undefined") return "km";
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    return raw === "en" ? "en" : "km";
  } catch {
    return "km";
  }
}

// Minimal in-file translation dictionary. Keep it small and additive — the
// audience is Cambodian so "km" is the source of truth; "en" carries the
// fallback we already use everywhere else. Add new keys as components opt in
// via the `useT()` hook.
type Dict = Record<string, Record<Language, string>>;

const DICT: Dict = {
  // Explore hero
  "explore.hero.title.before": { km: "ស្វែងរកកន្លែងរស់នៅដ៏ល្អឥតខ្ចោះ", en: "Find your perfect place to live" },
  "explore.hero.title.highlight": { km: "នៅទីនេះ", en: "Here" },
  "explore.hero.subtitle": {
    km: "ស្វែងរកកន្លែងសម្រាប់ការរស់នៅទៅអ្នកតាមតំបន់ ប្រភេទ និងតម្លៃ នៃតម្រូវការរបស់អ្នក។ ទាក់ទងភ្លាមៗទៅម្ចាស់បន្ទប់។",
    en: "Search for your perfect home by location, type, and price. Contact the host directly."
  },

  // Search bar
  "search.location.placeholder": { km: "ស្វែងរកនៅទីណា? ខេត្ត ស្រុក តំបន់…", en: "Where to? Province, district, area…" },
  "search.type.any": { km: "គ្រប់ប្រភេទទាំងអស់", en: "Any property type" },
  "search.type.title": { km: "ប្រភេទបន្ទប់", en: "Property type" },
  "search.sort.default": { km: "កំណត់តម្លៃ", en: "Sort by price" },
  "search.sort.asc": { km: "តម្លៃ៖ ទាបទៅខ្ពស់", en: "Price: low to high" },
  "search.sort.desc": { km: "តម្លៃ៖ ខ្ពស់ទៅទាប", en: "Price: high to low" },
  "search.submit": { km: "ស្វែងរក", en: "Search" },
  "search.clearLocation": { km: "សម្អាតទីតាំង", en: "Clear location" },
  "search.clearType": { km: "សម្អាតប្រភេទអចលនទ្រព្យ", en: "Clear property type" },
  "search.clearSort": { km: "សម្អាតការកំណត់តម្លៃ", en: "Clear sort" },

  // Property type labels
  "type.room": { km: "បន្ទប់", en: "Room" },
  "type.house": { km: "ផ្ទះ", en: "House" },
  "type.apartment": { km: "អាផាតមិន", en: "Apartment" },
  "type.condo": { km: "ខុនដូ", en: "Condo" },
  "type.flat": { km: "ផ្ទះល្វែង", en: "Flat" },
  "type.villa": { km: "វីឡា", en: "Villa" },

  // Explore listing block
  "explore.heading": { km: "មើលបន្ទប់ទាំងអស់", en: "Explore all rooms" },
  "explore.counter.available.one": { km: "{n} បន្ទប់ទំនេរ", en: "{n} room available right now" },
  "explore.counter.available.many": { km: "{n} បន្ទប់ទំនេរ", en: "{n} rooms available right now" },
  "explore.counter.inArea.one": { km: "{n} បន្ទប់នៅក្នុងតំបន់នេះ", en: "{n} room in this area" },
  "explore.counter.inArea.many": { km: "{n} បន្ទប់នៅក្នុងតំបន់នេះ", en: "{n} rooms in this area" },
  "explore.tab.list": { km: "បញ្ជី", en: "List" },
  "explore.tab.map": { km: "ផែនទី", en: "Map" },

  // Common buttons / actions
  "common.save": { km: "រក្សាទុក", en: "Save" },
  "common.saving": { km: "កំពុងរក្សាទុក…", en: "Saving…" },
  "common.cancel": { km: "បោះបង់", en: "Cancel" },
  "common.delete": { km: "លុប", en: "Delete" },
  "common.edit": { km: "កែប្រែ", en: "Edit" },
  "common.copy": { km: "ចម្លង", en: "Copy" },
  "common.close": { km: "បិទ", en: "Close" },
  "common.back": { km: "ត្រឡប់ក្រោយ", en: "Back" },
  "common.continue": { km: "បន្ត", en: "Continue" },
  "common.next": { km: "បន្ទាប់", en: "Next" },
  "common.previous": { km: "ពីមុន", en: "Previous" },
  "common.confirm": { km: "បញ្ជាក់", en: "Confirm" },
  "common.search": { km: "ស្វែងរក", en: "Search" },
  "common.add": { km: "បន្ថែម", en: "Add" },
  "common.remove": { km: "ដកចេញ", en: "Remove" },
  "common.loading": { km: "កំពុងផ្ទុក…", en: "Loading…" },
  "common.optional": { km: "(មិនតម្រូវ)", en: "(optional)" },
  "common.required": { km: "ចាំបាច់", en: "Required" },
  "common.yes": { km: "បាទ/ចាស", en: "Yes" },
  "common.no": { km: "ទេ", en: "No" },
  "common.clear": { km: "សម្អាត", en: "Clear" },
  "common.clearFilters": { km: "សម្អាតការស្វែងរក", en: "Clear filters" },
  "common.reset": { km: "កំណត់ឡើងវិញ", en: "Reset" },
  "common.publish": { km: "ផ្សព្វផ្សាយ", en: "Publish" },
  "common.publishing": { km: "កំពុងផ្សព្វផ្សាយ…", en: "Publishing…" },
  "common.update": { km: "ធ្វើបច្ចុប្បន្នភាព", en: "Update" },
  "common.tryAgain": { km: "ព្យាយាមម្តងទៀត", en: "Try again" },
  "common.dismiss": { km: "បិទ", en: "Dismiss" },
  "common.markAsRead": { km: "សម្គាល់ថាបានអាន", en: "Mark as read" },
  "common.markAllRead": { km: "សម្គាល់ទាំងអស់ថាបានអាន", en: "Mark all read" },
  "common.viewOnSite": { km: "មើលលើគេហទំព័រ", en: "View on site" },
  "common.justNow": { km: "ឥឡូវនេះ", en: "just now" },
  "common.minutesAgo": { km: "{n} នាទីមុន", en: "{n}m ago" },
  "common.hoursAgo": { km: "{n} ម៉ោងមុន", en: "{n}h ago" },
  "common.daysAgo": { km: "{n} ថ្ងៃមុន", en: "{n}d ago" },
  "common.unread": { km: "មិនទាន់អាន", en: "Unread" },
  "auth.checking": { km: "កំពុងពិនិត្យ session…", en: "Checking your session…" },
  "common.anonymousUser": { km: "អ្នកប្រើប្រាស់", en: "User" },

  // Navbar
  "nav.profile": { km: "ប្រវត្តិរូបរបស់អ្នក", en: "Your profile" },
  "nav.logIn": { km: "ចូល", en: "Log in" },
  "nav.listRoom": { km: "ដាក់បន្ទប់ជួល", en: "List room" },
  "nav.notifications.aria": { km: "ការជូនដំណឹង", en: "Notifications" },
  "nav.notifications.ariaWithCount": { km: "ការជូនដំណឹង ({n} មិនទាន់អាន)", en: "Notifications ({n} unread)" },
  "nav.view.user": { km: "អ្នកប្រើ", en: "User" },
  "nav.view.admin": { km: "អ្នកគ្រប់គ្រង", en: "Admin" },
  "nav.view.toggle.title": { km: "{current} — ចុចដើម្បីប្តូរទៅ {next}", en: "{current} view — tap to switch to {next}" },
  "nav.view.toggle.aria": { km: "ទិដ្ឋភាពបច្ចុប្បន្ន៖ {current}។ ចុចដើម្បីប្តូរទៅ {next}។", en: "Current view: {current}. Tap to switch to {next}." },
  "nav.languageToggle.aria": { km: "ប្តូរទៅអង់គ្លេស", en: "Switch to Khmer" },
  "language.km": { km: "ភាសាខ្មែរ", en: "Khmer" },
  "language.en": { km: "អង់គ្លេស", en: "English" },
  "language.toggle.title": { km: "{current} — ចុចដើម្បីប្តូរទៅ {next}", en: "{current} — tap to switch to {next}" },
  "language.toggle.aria": { km: "ភាសាបច្ចុប្បន្ន៖ {current}។ ចុចដើម្បីប្តូរទៅ {next}។", en: "Current language: {current}. Tap to switch to {next}." },

  // Bottom nav
  "bottomNav.home": { km: "ទំព័រដើម", en: "Home" },
  "bottomNav.profile": { km: "ប្រវត្តិរូប", en: "Profile" },
  "bottomNav.login": { km: "ចូល", en: "Login" },
  "bottomNav.listRoom.aria": { km: "ផ្សាយបន្ទប់របស់អ្នក", en: "List your room" },
  "bottomNav.primary.aria": { km: "ការរុករកសំខាន់", en: "Primary" },

  // Footer
  "footer.tagline": {
    km: "កន្លែងសាមញ្ញសម្រាប់ចែករំលែកបន្ទប់ជួលនៅកម្ពុជា។ ស្វែងរកបញ្ជី ឬផ្សាយបន្ទប់របស់អ្នក — យ៉ាងងាយស្រួល។",
    en: "A simple place to share rooms for rent in Cambodia. Browse listings or post your own — no fuss."
  },
  "footer.contact.heading": { km: "ទាក់ទងមកយើង", en: "Get in touch" },
  "footer.madeIn": { km: "បង្កើតនៅកម្ពុជា", en: "Made in Cambodia" },

  // Auth modal
  "auth.login.title": { km: "សូមស្វាគមន៍ត្រឡប់មកវិញ", en: "Welcome back" },
  "auth.login.subtitle": { km: "ចូលដោយប្រើលេខទូរស័ព្ទរបស់អ្នកដើម្បីបន្ត។", en: "Log in with your phone number to continue." },
  "auth.register.title": { km: "បង្កើតគណនីរបស់អ្នក", en: "Create your account" },
  "auth.register.subtitle": { km: "ចំណាយពេលតិចជាងមួយនាទី។", en: "It takes less than a minute." },
  "auth.field.phone": { km: "លេខទូរស័ព្ទ", en: "Phone number" },
  "auth.field.password": { km: "ពាក្យសម្ងាត់", en: "Password" },
  "auth.field.fullName": { km: "ឈ្មោះពេញ", en: "Full name" },
  "auth.field.fullName.placeholder": { km: "សុខា ចាន់", en: "Sokha Chan" },
  "auth.field.password.placeholder.short": { km: "យ៉ាងតិច៨តួអក្សរ", en: "At least 8 characters" },
  "auth.login.submit": { km: "ចូល", en: "Log in" },
  "auth.login.submitting": { km: "កំពុងចូល…", en: "Signing in…" },
  "auth.register.submit": { km: "បង្កើតគណនី", en: "Create account" },
  "auth.register.submitting": { km: "កំពុងបង្កើត…", en: "Creating…" },
  "auth.switch.toRegister.q": { km: "មិនទាន់មានគណនី?", en: "No account yet?" },
  "auth.switch.toRegister.cta": { km: "បង្កើតគណនី", en: "Create one" },
  "auth.switch.toLogin.q": { km: "មានគណនីរួចហើយមែនទេ?", en: "Already have an account?" },
  "auth.switch.toLogin.cta": { km: "ចូល", en: "Log in" },
  "auth.error.phone.invalid": { km: "បញ្ចូលលេខទូរស័ព្ទដែលត្រឹមត្រូវ (៨-៩ ខ្ទង់ បន្ទាប់ពី +855)។", en: "Enter a valid Cambodian phone number (8-9 digits after +855)." },
  "auth.error.phone.required": { km: "ត្រូវការលេខទូរស័ព្ទ", en: "Phone number is required." },
  "auth.error.password.tooShort": { km: "ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៨ តួអក្សរ។", en: "Password must be at least 8 characters." },
  "auth.error.name.required": { km: "បញ្ចូលឈ្មោះរបស់អ្នក។", en: "Enter your name." },
  "auth.field.confirmPassword": { km: "បញ្ជាក់ពាក្យសម្ងាត់", en: "Confirm password" },
  "auth.error.confirmPassword.mismatch": { km: "ពាក្យសម្ងាត់មិនត្រូវគ្នា។ សូមព្យាយាមម្ដងទៀត។", en: "Passwords don't match. Please try again." },
  "auth.error.disabled": { km: "គណនីនេះត្រូវបានបិទ។ សូមទាក់ទងអ្នកគ្រប់គ្រង។", en: "This account has been disabled. Please contact an admin." },
  "auth.error.notSignedIn": { km: "មិនបានចូលប្រើ", en: "Not signed in." },
  "auth.error.signInFailed": { km: "មិនអាចចូលបាន", en: "Unable to sign in" },
  "auth.error.signUpFailed": { km: "មិនអាចបង្កើតគណនីបាន", en: "Unable to create account" },
  "auth.field.phone.digitHint": { km: "{n} ខ្ទង់ — ត្រូវការ ៨ ឬ ៩", en: "{n} digits — need 8 or 9" },
  "auth.field.password.show": { km: "បង្ហាញពាក្យសម្ងាត់", en: "Show password" },
  "auth.field.password.hide": { km: "លាក់ពាក្យសម្ងាត់", en: "Hide password" },
  "auth.forgot.link": { km: "ភ្លេចពាក្យសម្ងាត់?", en: "Forgot password?" },
  "auth.forgot.title": { km: "កំណត់ពាក្យសម្ងាត់ថ្មី", en: "Reset password" },
  "auth.forgot.subtitle": { km: "បញ្ចូលលេខទូរស័ព្ទរបស់អ្នក ហើយយើងនឹងជួយអ្នក។", en: "Enter your phone number and we'll help you get back in." },
  "auth.forgot.findAccount": { km: "ស្វែងរកគណនី", en: "Find account" },
  "auth.forgot.finding": { km: "កំពុងស្វែងរក…", en: "Searching…" },
  "auth.forgot.newPassword": { km: "ពាក្យសម្ងាត់ថ្មី", en: "New password" },
  "auth.forgot.setPassword": { km: "កំណត់ពាក្យសម្ងាត់", en: "Set password" },
  "auth.forgot.setting": { km: "កំពុងរក្សាទុក…", en: "Saving…" },
  "auth.forgot.success.title": { km: "ចូលប្រើបានរួចរាល់!", en: "You're back in!" },
  "auth.forgot.success.body": { km: "ពាក្យសម្ងាត់ថ្មីត្រូវបានកំណត់ ហើយអ្នកបានចូលប្រើគណនីរបស់អ្នករួចហើយ។", en: "Your new password is set and you're now signed in." },
  "auth.forgot.back": { km: "ត្រឡប់ទៅចូលប្រើ", en: "Back to sign in" },
  "auth.forgot.notFound": { km: "រកមិនឃើញគណនីសម្រាប់លេខទូរស័ព្ទនេះ។", en: "No account found for this phone number." },
  "auth.forgot.noSupport": { km: "ការកំណត់ពាក្យសម្ងាត់ម្ដងទៀតមិនត្រូវបានគាំទ្រ។ សូមទាក់ទងផ្នែកជំនួយ។", en: "Password reset is not supported in this mode. Please contact support." },

  // Profile page
  "profile.editProfile": { km: "កែប្រែប្រវត្តិរូប", en: "Edit profile" },
  "profile.share": { km: "ចែករំលែកព័ត៌មាន", en: "Share profile" },
  "profile.share.title": { km: "ប្រវត្តិរូបរបស់ {name} នៅ Joul.KH", en: "{name} on Joul.KH" },
  "profile.share.text": { km: "មើលបន្ទប់ដែលផ្សាយដោយ {name} នៅ Joul.KH។", en: "Check out rooms listed by {name} on Joul.KH." },
  "profile.logOut": { km: "ចេញ", en: "Log out" },
  "profile.loggingOut": { km: "កំពុងចេញ…", en: "Logging out…" },
  "profile.myListings": { km: "បន្ទប់របស់ខ្ញុំ", en: "My listings" },
  "profile.listARoom": { km: "ដាក់បន្ទប់ជួល", en: "List a room" },
  "profile.empty.title": { km: "មិនទាន់មានបន្ទប់ផ្សព្វផ្សាយទេ", en: "No listings yet" },
  "profile.empty.body": { km: "ផ្សាយបន្ទប់ដំបូងរបស់អ្នកដើម្បីចាប់ផ្តើមទទួលការទាក់ទងពីអ្នកជួល។", en: "Publish your first room to start receiving messages from renters." },
  "profile.empty.cta": { km: "បង្កើតបន្ទប់ដំបូងរបស់អ្នក", en: "Create your first listing" },
  "profile.menu.aria": { km: "ជម្រើសប្រវត្តិរូប", en: "Profile options" },
  "profile.occupied": { km: "មានអ្នកជួល", en: "Occupied" },
  "profile.autoOccupied.note": {
    km: "បិទដោយស្វ័យប្រវត្តិ — គ្មានសកម្មភាពក្នុងរយៈពេល {days} ថ្ងៃ។ ចុចដើម្បីកំណត់ជាអាចជួលបានម្តងទៀត។",
    en: "Auto-marked Occupied — no activity for {days} days. Tap to mark Available again."
  },
  "profile.autoOccupied.markAvailable": { km: "សម្គាល់ជាអាចជួលបាន", en: "Mark Available" },
  "profile.month": { km: "/ ខែ", en: "/ month" },
  "profile.view.grid": { km: "ក្រឡា", en: "Grid" },
  "profile.view.list": { km: "បញ្ជី", en: "List" },
  "profile.list.col.title": { km: "ចំណងជើង", en: "Title" },
  "profile.list.col.status": { km: "ស្ថានភាព", en: "Status" },
  "profile.list.col.type": { km: "ប្រភេទ", en: "Type" },
  "profile.list.col.details": { km: "ព័ត៌មាន", en: "Details" },
  "profile.list.col.price": { km: "តម្លៃ", en: "Price" },
  "profile.available": { km: "បន្ទប់ទំនេរ", en: "Available" },

  // Edit profile modal
  "profile.edit.title": { km: "កែប្រែប្រវត្តិរូប", en: "Edit profile" },
  "profile.edit.name": { km: "ឈ្មោះ", en: "Name" },
  "profile.edit.loginPhone": { km: "លេខទូរស័ព្ទចូល", en: "Login phone" },
  "profile.edit.loginPhone.hint": { km: "អ្នកចូលដោយលេខនេះ។ ការប្តូរវាមិនប៉ះពាល់ដល់ព័ត៌មានទាក់ទងលើបញ្ជីទេ។", en: "You sign in with this number. Changing it doesn't affect the contact info you publish on listings." },
  "profile.edit.photo.upload": { km: "ផ្ទុករូបភាព", en: "Upload photo" },
  "profile.edit.photo.change": { km: "ប្តូររូបភាព", en: "Change photo" },
  "profile.edit.photo.loading": { km: "កំពុងផ្ទុក…", en: "Loading…" },
  "profile.edit.photo.error.fileType": { km: "សូមជ្រើសរើសឯកសាររូបភាព។", en: "Please choose an image file." },
  "profile.edit.photo.error.load": { km: "មិនអាចផ្ទុករូបភាពនេះបាន។", en: "Could not load that image." },
  "profile.edit.error.saveFailed": { km: "មិនអាចរក្សាការផ្លាស់ប្តូរ។", en: "Could not save changes." },

  // Property type picker (profile)
  "pick.type.title": { km: "តើអ្នកចង់ផ្សាយអ្វី?", en: "What are you listing?" },
  "pick.type.aria": { km: "ជ្រើសរើសប្រភេទកន្លែង", en: "Pick a property type" },
  "pick.type.room.hint": { km: "បន្ទប់មួយក្នុងផ្ទះ", en: "A single room within a property" },
  "pick.type.apartment.hint": { km: "អាផាតមិនឯករាជ្យក្នុងអគារ", en: "Self-contained unit in a building" },
  "pick.type.condo.hint": { km: "ខុនដូដែលជាកម្មសិទ្ធិឯកជនក្នុងគម្រោងគ្រប់គ្រង", en: "Privately-owned unit in a managed complex" },
  "pick.type.flat.hint": { km: "ផ្ទះតូចមួយជាន់", en: "Small one-floor home" },
  "pick.type.house.hint": { km: "ផ្ទះឯករាជ្យ", en: "Standalone home" },
  "pick.type.villa.hint": { km: "ផ្ទះវីឡាធំ", en: "Larger standalone home" },

  // Listing action menu
  "listing.menu.aria": { km: "ជម្រើសបញ្ជី", en: "Listing options" },
  "listing.menu.markOccupied": { km: "សម្គាល់ថាមានអ្នកជួល", en: "Mark as occupied" },
  "listing.menu.markAvailable": { km: "សម្គាល់ថាបន្ទប់ទំនេរ", en: "Mark as available" },
  "listing.delete.confirm.title": { km: "លុបបញ្ជីនេះ?", en: "Delete this listing?" },
  "listing.delete.confirm.body": { km: "នឹងត្រូវលុបចោល។ មិនអាចត្រឡប់បានទេ។", en: "will be removed. This can't be undone." },

  // Toast messages
  "toast.profile.updated": { km: "ប្រវត្តិរូបបានធ្វើបច្ចុប្បន្នភាព។", en: "Profile updated." },
  "toast.profile.linkCopied": { km: "បានចម្លងតំណប្រវត្តិរូប។", en: "Profile link copied." },
  "toast.profile.messageCopied": { km: "បានចម្លងសារ — បិទភ្ជាប់ដើម្បីចែករំលែក។", en: "Message copied — paste it anywhere to share." },
  "toast.profile.shareFailed": { km: "ចែករំលែកមិនបានសម្រេច។ សូមព្យាយាមម្តងទៀត។", en: "Couldn't share. Please try again." },
  "toast.listing.published": { km: "\"{title}\" ត្រូវបានផ្សព្វផ្សាយ។", en: "\"{title}\" is now published." },
  "toast.listing.deleted": { km: "\"{title}\" បានលុប។", en: "\"{title}\" deleted." },
  "toast.listing.occupied": { km: "\"{title}\" សម្គាល់ថាមានអ្នកជួល។", en: "\"{title}\" marked as occupied." },
  "toast.listing.updated": { km: "\"{title}\" ត្រូវបានធ្វើបច្ចុប្បន្នភាព។", en: "\"{title}\" updated." },
  "toast.listing.available": { km: "\"{title}\" អាចជួលបានឥឡូវនេះ។", en: "\"{title}\" is now available." },
  "toast.form.cleared": { km: "ទម្រង់បានសម្អាត។", en: "Form cleared." },
  "toast.notifications.markedOne": { km: "ការជូនដំណឹង ១ ត្រូវបានសម្គាល់ថាបានអាន។", en: "1 notification marked as read." },
  "toast.notifications.markedMany": { km: "ការជូនដំណឹង {n} ត្រូវបានសម្គាល់ថាបានអាន។", en: "{n} notifications marked as read." },

  // Room detail page
  "room.notFound.title": { km: "រកមិនឃើញបន្ទប់", en: "Room not found" },
  "room.notFound.body": { km: "បន្ទប់ដែលអ្នកស្វែងរកមិនមាន ឬត្រូវបានដកចេញ។", en: "The listing you're looking for doesn't exist or has been removed." },
  "room.notFound.cta": { km: "ត្រឡប់ទៅទំព័រស្វែងរក", en: "Back to Explore" },
  "room.stat.bed": { km: "បន្ទប់", en: "Bed" },
  "room.stat.bed.many": { km: "បន្ទប់", en: "Beds" },
  "room.stat.floor": { km: "ជាន់", en: "Floor" },
  "room.section.about": { km: "អំពីកន្លែងនេះ", en: "About this place" },
  "room.section.amenities": { km: "កន្លែងនេះមានផ្តល់ជូន", en: "What this place offers" },
  "room.section.fees": { km: "តម្លៃ និងថ្លៃសេវា", en: "Fees & utilities" },
  "room.section.similar": { km: "បន្ទប់ស្រដៀងគ្នា", en: "Similar rooms" },
  "room.section.location": { km: "ទីតាំង", en: "Location" },
  "room.section.host": { km: "ទាក់ទងម្ចាស់", en: "Contact the host" },
  "room.host.listedBy": { km: "ផ្សាយដោយ", en: "Listed by" },
  "room.host.viewProfile": { km: "មើលប្រវត្តិរូប →", en: "View profile →" },
  "room.host.reportListing": { km: "រាយការណ៍អំពីបញ្ជីនេះ", en: "Report this listing" },

  // Public host profile (/users/[uid])
  "host.notFound.title": { km: "មិនឃើញម្ចាស់ផ្ទះនេះ", en: "Host not found" },
  "host.notFound.body": { km: "យើងមិនអាចស្វែងរកម្ចាស់ផ្ទះនេះបានទេ ឬគាត់មិនមានបន្ទប់ផ្សាយឡើយ។", en: "We couldn't find this host, or they haven't listed any rooms yet." },
  "host.summary.available.one": { km: "មាន {n} បន្ទប់អាចជួលបាន", en: "{n} room available" },
  "host.summary.available.many": { km: "មាន {n} បន្ទប់អាចជួលបាន", en: "{n} rooms available" },
  "host.listings.heading": { km: "បន្ទប់ផ្សេងទៀតពីម្ចាស់នេះ", en: "More rooms from this host" },
  "host.empty.title": { km: "មិនមានបន្ទប់ផ្សាយឥឡូវនេះ", en: "No rooms available right now" },
  "host.empty.body": { km: "ម្ចាស់ផ្ទះនេះមិនទាន់មានបញ្ជីដែលនៅទំនេរ។", en: "This host doesn't have any open listings yet." },
  "host.empty.allOccupied.one": { km: "បន្ទប់ {n} របស់ពួកគេ ត្រូវបានជួលរួចហើយ។", en: "Their {n} listing is currently rented out." },
  "host.empty.allOccupied.many": { km: "បន្ទប់ទាំង {n} របស់ពួកគេ ត្រូវបានជួលរួចទាំងអស់។", en: "All {n} of their listings are currently rented out." },
  "room.contactLabel.phone": { km: "ទូរស័ព្ទ", en: "Phone" },
  "room.contactLabel.telegram": { km: "តេឡេក្រាម", en: "Telegram" },
  "room.fee.rent.daily": { km: "ថ្លៃជួលប្រចាំថ្ងៃ", en: "Daily rent" },
  "room.fee.rent.weekly": { km: "ថ្លៃជួលប្រចាំសប្តាហ៍", en: "Weekly rent" },
  "room.fee.rent.monthly": { km: "ថ្លៃជួលប្រចាំខែ", en: "Monthly rent" },
  "room.fee.rent.yearly": { km: "ថ្លៃជួលប្រចាំឆ្នាំ", en: "Yearly rent" },
  "room.fee.deposit": { km: "ប្រាក់កក់ (មុនចូលនៅ)", en: "Deposit (before move-in)" },
  "room.fee.electricity": { km: "អគ្គិសនី", en: "Electricity" },
  "room.fee.electricity.unit": { km: "/ កវ៉ាត់ម៉ោង", en: "/ kWh" },
  "room.fee.water": { km: "ទឹក", en: "Water" },
  "room.fee.water.unit": { km: "/ ម៉ែត្រគូប", en: "/ m³" },
  "room.fee.wifi": { km: "វ៉ាយហ្វាយ", en: "Wi-Fi" },
  "room.fee.wifi.unit": { km: "/ ខែ", en: "/ month" },
  "room.suffix.daily": { km: "/ ថ្ងៃ", en: "/ day" },
  "room.suffix.weekly": { km: "/ សប្តាហ៍", en: "/ week" },
  "room.suffix.monthly": { km: "/ ខែ", en: "/ month" },
  "room.suffix.yearly": { km: "/ ឆ្នាំ", en: "/ year" },
  "room.location.openMaps": { km: "បើកក្នុង Maps ↗", en: "Open in Maps ↗" },
  "room.location.showMap": { km: "បង្ហាញផែនទី", en: "Show map" },
  "room.location.loadsGoogleMaps": { km: "ផ្ទុក Google Maps", en: "Loads Google Maps" },
  "room.cta.location": { km: "ទីតាំង", en: "Location" },
  "room.cta.contact": { km: "ទាក់ទង", en: "Contact" },
  "room.report.title": { km: "រាយការណ៍អំពីបញ្ជីនេះ", en: "Report this listing" },
  "room.report.success.title": { km: "អរគុណសម្រាប់ការជូនដំណឹង", en: "Thanks for the heads up" },
  "room.report.success.body": { km: "ក្រុមការងារនឹងពិនិត្យបញ្ជីនេះឆាប់ៗ។ អ្នកអាចបិទប្រអប់នេះបាន។", en: "Our team will review this listing soon. You can close this dialog." },
  "room.report.done": { km: "រួចរាល់", en: "Done" },
  "room.report.intro": { km: "ជ្រើសរើសហេតុផលដែលពិពណ៌នាបញ្ហានេះបានល្អបំផុត។ ការបន្ថែមព័ត៌មានលម្អិតជួយឱ្យយើងពិនិត្យលឿនជាងមុន។", en: "Pick the reason that best describes the issue. Adding details helps us review faster." },
  "room.report.reason.label": { km: "ហេតុផល", en: "Reason" },
  "room.report.reason.misleading": { km: "រូបភាព ឬព័ត៌មានបំភាន់", en: "Misleading photos or details" },
  "room.report.reason.priceWrong": { km: "តម្លៃហាក់ដូចជាមិនត្រឹមត្រូវ", en: "Price seems wrong" },
  "room.report.reason.alreadyRented": { km: "ជួលរួចហើយ", en: "Already rented" },
  "room.report.reason.suspicious": { km: "គួរឱ្យសង្ស័យ ឬបោកប្រាស់", en: "Suspicious or scam" },
  "room.report.reason.other": { km: "ផ្សេងទៀត", en: "Other" },
  "room.report.details.label": { km: "ព័ត៌មានលម្អិត", en: "Details" },
  "room.report.details.placeholder": { km: "តើអ្នកសម្គាល់ឃើញអ្វីខ្លះ? អ្វីដែលជួយយើងពិនិត្យ។", en: "What did you notice? Anything that helps us review." },
  "room.report.submit": { km: "ផ្ញើរបាយការណ៍", en: "Submit report" },
  "room.report.guestName": { km: "ភ្ញៀវម្នាក់", en: "A guest" },
  "room.report.notif.title": { km: "បញ្ជីត្រូវបានរាយការណ៍ដោយអ្នកប្រើ", en: "Listing reported by a user" },
  "room.report.notif.body": { km: "{reporter} បានរាយការណ៍ \"{title}\" — {reason}។{details}", en: "{reporter} flagged \"{title}\" — {reason}.{details}" },
  "room.report.notif.details": { km: " ព័ត៌មានលម្អិត៖ {value}", en: " Details: {value}" },
  "roomCard.floor.short": { km: "ជាន់", en: "F" },
  "roomCard.viewDetails": { km: "មើលលម្អិត →", en: "View details →" },

  // List-room form
  "listRoom.nav.profile": { km: "ប្រវត្តិរូប", en: "Profile" },
  "listRoom.title.template": { km: "ផ្សាយ", en: "List your" },
  "listRoom.title.highlight.fallback": { km: "បន្ទប់", en: "Room" },
  "listRoom.subtitle": { km: "វាយ ឬចុចលើវាលណាមួយខាងក្រោម — ការរៀបចំគឺជាអ្វីដែលអ្នកជួលនឹងឃើញ។", en: "Type or tap into any field below — the layout is how renters will see it." },
  "listRoom.editTitle.template": { km: "កែប្រែ", en: "Edit your" },
  "listRoom.editSubtitle": { km: "ធ្វើបច្ចុប្បន្នភាពព័ត៌មាន រួចចុចរក្សាទុក។", en: "Update the details, then save your changes." },
  "listRoom.photos.heading": { km: "រូបភាព", en: "Photos" },
  "listRoom.photos.add": { km: "បន្ថែម", en: "Add" },
  "listRoom.photos.more": { km: "ច្រើនទៀត", en: "More" },
  "listRoom.photos.remove.aria": { km: "ដករូបភាព", en: "Remove photo" },
  "listRoom.photos.oversized.one": { km: "រូបភាព ១ ធំជាង ១០ MB ហើយត្រូវបានរំលង។", en: "1 photo is larger than 10 MB and was skipped." },
  "listRoom.photos.oversized.many": { km: "រូបភាព {n} ធំជាង ១០ MB ហើយត្រូវបានរំលង។", en: "{n} photos are larger than 10 MB and were skipped." },
  "listRoom.titleField.heading": { km: "ចំណងជើង", en: "Title" },
  "listRoom.titleField.placeholder": { km: "ឧ. ស្ទូឌីយោកក់ស្តៅជិតមាត់ទន្លេ", en: "e.g. Cozy studio near Riverside" },
  "listRoom.details.heading": { km: "ព័ត៌មានលម្អិត", en: "details" },
  "listRoom.details.bed.one": { km: "បន្ទប់គេង ១", en: "1 bed" },
  "listRoom.details.bed.many": { km: "បន្ទប់គេង {n}", en: "{n} beds" },
  "listRoom.details.floor.one": { km: "ជាន់ ១", en: "1 floor" },
  "listRoom.details.floor.many": { km: "ជាន់ {n}", en: "{n} floors" },
  "listRoom.details.edit": { km: "កែប្រែលម្អិត", en: "Edit details" },
  "listRoom.about.heading": { km: "អំពីកន្លែងនេះ", en: "About this place" },
  "listRoom.about.placeholder": { km: "ប្រាប់អ្នកជួលនូវអ្វីដែលនឹងជួប — សង្កាត់ បរិយាកាស អ្វីពិសេស។", en: "Tell renters what to expect — the neighbourhood, vibe, anything special." },
  "listRoom.amenities.heading": { km: "កន្លែងនេះមាន", en: "What this place offers" },
  "listRoom.amenities.add": { km: "បន្ថែម", en: "Add" },
  "listRoom.fees.heading": { km: "តម្លៃ និងថ្លៃសេវា", en: "Fees & utilities" },
  "listRoom.fees.rentLabel": { km: "ថ្លៃជួល", en: "Rent fee" },
  "listRoom.fees.other.fallback": { km: "ផ្សេងទៀត", en: "Other" },
  "listRoom.fees.editFees": { km: "កែប្រែថ្លៃ", en: "Edit fees" },
  "listRoom.fees.addFees": { km: "បន្ថែមថ្លៃ", en: "Add fees" },
  "listRoom.fees.fillIn": { km: "បំពេញព័ត៌មានថ្លៃរបស់អ្នកនៅទីនេះ។", en: "Fill in your fee details here." },
  "listRoom.fees.required": { km: "ត្រូវមានយ៉ាងតិចមួយ", en: "At least one is required" },
  "listRoom.location.heading": { km: "ទីតាំង", en: "Location" },
  "listRoom.location.edit": { km: "កែប្រែទីតាំង", en: "Edit location" },
  "listRoom.location.set": { km: "កំណត់ទីតាំង", en: "Set location" },
  "listRoom.location.pin.set": { km: "កំណត់ចំណុចលើផែនទី", en: "Set a pin on the map" },
  "listRoom.location.pin.move": { km: "ផ្លាស់ប្តូរចំណុច", en: "Move pin" },
  "listRoom.contact.heading": { km: "ព័ត៌មានទាក់ទង", en: "Contact info" },
  "listRoom.contact.edit": { km: "កែប្រែទាក់ទង", en: "Edit contact" },
  "listRoom.contact.add": { km: "បន្ថែមទាក់ទង", en: "Add contact" },
  "listRoom.contact.phones.heading": { km: "លេខទូរស័ព្ទ", en: "Phone numbers" },
  "listRoom.contact.telegram.heading": { km: "តេឡេក្រាម", en: "Telegram" },
  "listRoom.bottomBar.clear": { km: "សម្អាត", en: "Clear" },
  "listRoom.bottomBar.cancel": { km: "បោះបង់", en: "Cancel" },
  "listRoom.bottomBar.publish": { km: "ផ្សាយ", en: "Publish" },
  "listRoom.bottomBar.publishing": { km: "កំពុងផ្សាយ…", en: "Publishing…" },
  "listRoom.bottomBar.create": { km: "បង្កើត", en: "Create" },
  "listRoom.bottomBar.creating": { km: "កំពុងបង្កើត…", en: "Creating…" },
  "listRoom.confirmClear.title": { km: "សម្អាតគ្រប់វាល?", en: "Clear all fields?" },
  "listRoom.confirmClear.body": { km: "នេះនឹងលុបចេញអ្វីៗដែលអ្នកបានបញ្ចូល។", en: "This will remove everything you've entered." },
  "listRoom.confirmClear.confirm": { km: "សម្អាត", en: "Clear" },
  "listRoom.error.titleRequired": { km: "បន្ថែមចំណងជើងសម្រាប់ការផ្សាយរបស់អ្នក។", en: "Add a title for your listing." },
  "listRoom.error.descriptionRequired": { km: "បន្ថែមការពិពណ៌នាខ្លី។", en: "Add a short description." },
  "listRoom.error.provinceRequired": { km: "ជ្រើសរើសខេត្តសម្រាប់បញ្ជីរបស់អ្នក។", en: "Pick a province for your listing." },
  "listRoom.error.rentRequired": { km: "កំណត់ចំនួនថ្លៃជួលប្រចាំខែ។", en: "Set a monthly rent amount." },
  "listRoom.error.signInRequired": { km: "អ្នកត្រូវចូលដើម្បីផ្សាយបញ្ជី។", en: "You need to be signed in to publish a listing." },
  "listRoom.error.saveFailed": { km: "មិនអាចរក្សាបញ្ជី។", en: "Could not save the listing." },
  "listRoom.notif.title": { km: "បញ្ជីថ្មីត្រូវបានបង្ហោះ", en: "New listing posted" },
  "listRoom.notif.body": { km: "{owner} បានផ្សាយ \"{title}\" សម្រាប់ ${price}{suffix}។", en: "{owner} published \"{title}\" for ${price}{suffix}." },
  "listRoom.copyPrefix": { km: "ច្បាប់ចម្លងនៃ", en: "Copy of" },
  "listRoom.modal.editDetails.title": { km: "កែប្រែព័ត៌មានលម្អិត", en: "Edit details" },
  "listRoom.modal.editAmenities.title": { km: "ជ្រើសរើសសេវាកម្ម", en: "Select amenities" },
  "listRoom.modal.editFees.title": { km: "កែប្រែថ្លៃ", en: "Edit fees" },
  "listRoom.modal.editLocation.title": { km: "កែប្រែទីតាំង", en: "Edit location" },
  "listRoom.modal.editPin.title": { km: "កំណត់ចំណុចលើផែនទី", en: "Set pin on map" },
  "listRoom.modal.editContact.title": { km: "កែប្រែទាក់ទង", en: "Edit contact" },
  "listRoom.modal.done": { km: "រួចរាល់", en: "Done" },
  "listRoom.field.bedrooms": { km: "ចំនួនបន្ទប់គេង", en: "Bedrooms" },
  "listRoom.field.area": { km: "ផ្ទៃក្រឡា (m²)", en: "Area (m²)" },
  "listRoom.field.floor": { km: "ជាន់", en: "Floor" },
  "listRoom.field.propertyType": { km: "ប្រភេទកន្លែង", en: "Property type" },
  "listRoom.field.rentPeriod": { km: "ខួប", en: "Period" },
  "listRoom.field.price": { km: "តម្លៃ ($)", en: "Price ($)" },
  "listRoom.field.feeAmount": { km: "ចំនួន ($)", en: "Amount ($)" },
  "listRoom.field.feeType": { km: "ប្រភេទថ្លៃ", en: "Fee type" },
  "listRoom.field.feeLabel": { km: "ឈ្មោះ", en: "Label" },
  "listRoom.field.feeUnit": { km: "ឯកតា (មិនចាំបាច់)", en: "Unit (optional)" },
  "listRoom.field.addFee": { km: "បន្ថែមថ្លៃ", en: "Add fee" },
  "listRoom.location.address": { km: "អាសយដ្ឋាន", en: "Address" },
  "listRoom.location.address.placeholder": { km: "លេខផ្ទះ និងផ្លូវ", en: "Street address" },
  "listRoom.contact.phone.add": { km: "បន្ថែមលេខទូរស័ព្ទ", en: "Add phone" },
  "listRoom.contact.telegram.add": { km: "បន្ថែមតេឡេក្រាម", en: "Add Telegram" },
  "feeType.rent": { km: "ថ្លៃជួលប្រចាំខែ", en: "Monthly rent" },
  "feeType.deposit": { km: "ប្រាក់កក់", en: "Deposit" },
  "feeType.electricity": { km: "អគ្គិសនី", en: "Electricity" },
  "feeType.water": { km: "ទឹក", en: "Water" },
  "feeType.wifi": { km: "វ៉ាយហ្វាយ", en: "Wi-Fi" },
  "feeType.service": { km: "ថ្លៃសេវា", en: "Service charge" },
  "feeType.parking": { km: "ចំណតរថយន្ត", en: "Parking" },
  "feeType.other": { km: "ផ្សេងទៀត", en: "Other" },
  "period.daily": { km: "ប្រចាំថ្ងៃ", en: "Daily" },
  "period.weekly": { km: "ប្រចាំសប្តាហ៍", en: "Weekly" },
  "period.monthly": { km: "ប្រចាំខែ", en: "Monthly" },
  "period.yearly": { km: "ប្រចាំឆ្នាំ", en: "Yearly" },

  // User notifications page
  "userNotif.title": { km: "ការជូនដំណឹង", en: "Notifications" },
  "userNotif.subtitle": { km: "សារ និងការអាប់ដេតពីក្រុមការងារ Joul។", en: "Messages and updates from the Joul team." },
  "userNotif.empty.title": { km: "មិនទាន់មានការជូនដំណឹង", en: "No notifications yet" },
  "userNotif.empty.body": { km: "នៅពេលក្រុមការងារ Joul ផ្ញើការអាប់ដេត វានឹងបង្ហាញនៅទីនេះ។", en: "When the Joul team sends an update, it will show up here." },
  "userNotif.back.aria": { km: "ត្រឡប់ទៅប្រវត្តិរូប", en: "Back to profile" },

  // --- Admin: shell / floating nav ---
  "admin.nav.aria": { km: "អ្នកគ្រប់គ្រង", en: "Admin" },
  "admin.nav.rooms": { km: "បន្ទប់", en: "Rooms" },
  "admin.nav.users": { km: "អ្នកប្រើប្រាស់", en: "Users" },
  "admin.nav.notifications": { km: "សារ", en: "Messages" },
  "admin.nav.settings": { km: "ការកំណត់", en: "Settings" },
  "admin.shell.checking": { km: "កំពុងពិនិត្យសិទ្ធិចូលប្រើរបស់អ្នក…", en: "Checking your access…" },
  "admin.denied.title": { km: "សម្រាប់អ្នកគ្រប់គ្រងតែប៉ុណ្ណោះ", en: "Admins only" },
  "admin.denied.body.signedIn": {
    km: "តំបន់នេះមានកំណត់សម្រាប់អ្នកគ្រប់គ្រង Joul។ សូមចូលដោយគណនីអ្នកគ្រប់គ្រងដើម្បីបន្ត។",
    en: "This area is restricted to Joul admins. Sign in with an admin account to continue."
  },
  "admin.denied.body.signedOut": {
    km: "ចូលដោយគណនីអ្នកគ្រប់គ្រងដើម្បីគ្រប់គ្រងវេទិកា Joul។",
    en: "Sign in with an admin account to manage the Joul platform."
  },
  "admin.denied.backToExplore": { km: "ត្រឡប់ទៅទំព័រស្វែងរក", en: "Back to explore" },
  "admin.denied.switchAccount": { km: "ប្តូរគណនី", en: "Switch account" },

  // --- Admin: shared filter labels ---
  "admin.filter.anyStatus": { km: "គ្រប់ស្ថានភាព", en: "Any status" },
  "admin.filter.anyType": { km: "គ្រប់ប្រភេទ", en: "Any type" },
  "admin.filter.anyRole": { km: "គ្រប់តួនាទី", en: "Any role" },
  "admin.filter.anyLocation": { km: "គ្រប់ទីតាំង", en: "Any location" },
  "admin.filter.anyPrice": { km: "គ្រប់តម្លៃ", en: "Any price" },
  "admin.filter.anyCreatedDate": { km: "គ្រប់កាលបរិច្ឆេទបង្កើត", en: "Any created date" },
  "admin.filter.showFilters": { km: "បង្ហាញតម្រង", en: "Show filters" },
  "admin.filter.hideFilters": { km: "លាក់តម្រង", en: "Hide filters" },
  "admin.filter.statusLabel": { km: "ស្ថានភាព", en: "Status" },
  "admin.filter.typeLabel": { km: "ប្រភេទកន្លែង", en: "Property type" },
  "admin.filter.roleLabel": { km: "តួនាទី", en: "Role" },
  "admin.role.user": { km: "អ្នកប្រើ", en: "User" },
  "admin.role.admin": { km: "អ្នកគ្រប់គ្រង", en: "Admin" },
  "admin.status.active": { km: "សកម្ម", en: "Active" },
  "admin.status.disabled": { km: "បានបិទ", en: "Disabled" },
  "admin.status.available": { km: "អាចជួលបាន", en: "Available" },
  "admin.status.occupied": { km: "មានអ្នកជួល", en: "Occupied" },
  "admin.rowActions.aria": { km: "សកម្មភាពលើជួរ", en: "Row actions" },

  // --- Admin: Rooms page ---
  "admin.rooms.title": { km: "បន្ទប់", en: "Rooms" },
  "admin.rooms.subtitle": { km: "មើល កែប្រែ សម្គាល់ភាពអាចជួលបាន ឬលុបបញ្ជីបន្ទប់។", en: "View, edit, mark availability, or delete room listings." },
  "admin.rooms.search.placeholder": { km: "ស្វែងរកចំណងជើង អាសយដ្ឋាន ឬម្ចាស់", en: "Search title, address, or owner" },
  "admin.rooms.addRoom": { km: "បន្ថែមបន្ទប់", en: "Add room" },
  "admin.rooms.empty": { km: "មិនមានបន្ទប់ត្រូវនឹងការស្វែងរកនេះ។", en: "No rooms match this search." },
  "admin.rooms.location.openInMaps": { km: "បើកនៅក្នុង Google Maps", en: "Open in Google Maps" },
  "admin.rooms.stat.rooms": { km: "បន្ទប់", en: "Rooms" },
  "admin.rooms.stat.available": { km: "អាចជួលបាន", en: "Available" },
  "admin.rooms.stat.occupied": { km: "មានអ្នកជួល", en: "Occupied" },
  "admin.rooms.stat.types": { km: "ប្រភេទកន្លែង", en: "Property types" },
  "admin.rooms.stat.availableHint": { km: "{n} អាចជួលបាន", en: "{n} available" },
  "admin.rooms.stat.allOccupied": { km: "មានអ្នកជួលទាំងអស់", en: "All occupied" },
  "admin.rooms.stat.openToRenters": { km: "បើកសម្រាប់អ្នកជួល", en: "Open to renters" },
  "admin.rooms.stat.noneOccupied": { km: "មិនមានអ្នកជួល", en: "None occupied" },
  "admin.rooms.stat.currentlyRented": { km: "កំពុងជួល", en: "Currently rented" },
  "admin.rooms.stat.noRooms": { km: "មិនទាន់មានបន្ទប់", en: "No rooms yet" },
  "admin.rooms.stat.distinctCategories": { km: "ប្រភេទផ្សេងគ្នា", en: "Distinct categories" },
  "admin.rooms.col.listing": { km: "បញ្ជី", en: "Listing" },
  "admin.rooms.col.owner": { km: "ម្ចាស់", en: "Owner" },
  "admin.rooms.col.location": { km: "ទីតាំង", en: "Location" },
  "admin.rooms.col.price": { km: "តម្លៃ", en: "Price" },
  "admin.rooms.col.status": { km: "ស្ថានភាព", en: "Status" },
  "admin.rooms.col.daysAvailable": { km: "ចំនួនថ្ងៃទំនេរ", en: "Days available" },
  "admin.rooms.col.daysAvailable.sort.none": { km: "តម្រៀបតាមចំនួនថ្ងៃទំនេរ", en: "Sort by days available" },
  "admin.rooms.col.daysAvailable.sort.desc": { km: "តម្រៀបហើយ: ច្រើន → តិច", en: "Sorted: large → small" },
  "admin.rooms.col.daysAvailable.sort.asc": { km: "តម្រៀបហើយ: តិច → ច្រើន", en: "Sorted: small → large" },
  "admin.rooms.col.actions": { km: "សកម្មភាព", en: "Actions" },
  "admin.rooms.action.viewOnSite": { km: "មើលលើគេហទំព័រ", en: "View on site" },
  "admin.rooms.action.edit": { km: "កែប្រែ", en: "Edit" },
  "admin.rooms.action.markAvailable": { km: "សម្គាល់ថាអាចជួលបាន", en: "Mark available" },
  "admin.rooms.action.markOccupied": { km: "សម្គាល់ថាមានអ្នកជួល", en: "Mark occupied" },
  "admin.rooms.action.delete": { km: "លុប", en: "Delete" },
  "admin.rooms.delete.title": { km: "លុបបន្ទប់?", en: "Delete room?" },
  "admin.rooms.delete.body.suffix": { km: " នឹងត្រូវលុបចេញ។ មិនអាចសង្គ្រោះបានទេក្នុងទិន្នន័យសាកល្បង។", en: " will be removed. This can't be undone in mock data." },

  // --- Admin: Listing edit modal ---
  "admin.listingEdit.title": { km: "កែប្រែបញ្ជី", en: "Edit listing" },
  "admin.listingEdit.field.title": { km: "ចំណងជើង", en: "Title" },
  "admin.listingEdit.field.price": { km: "តម្លៃប្រចាំខែ (ដុល្លារ)", en: "Monthly price (USD)" },
  "admin.listingEdit.field.owner": { km: "ម្ចាស់", en: "Owner" },
  "admin.listingEdit.field.notInDirectory": { km: "{name} (មិននៅក្នុងបញ្ជីអ្នកប្រើប្រាស់)", en: "{name} (not in user directory)" },
  "admin.listingEdit.toggle.label": { km: "សម្គាល់ថាមានអ្នកជួល", en: "Marked as occupied" },
  "admin.listingEdit.toggle.hint": { km: "លាក់បញ្ជីពីសំណើថ្មីៗរបស់អ្នកជួល។", en: "Hide the listing from new renter inquiries." },
  "admin.listingEdit.error.required": { km: "ត្រូវការចំណងជើង និងតម្លៃមិនអវិជ្ជមាន។", en: "Title and a non-negative price are required." },
  "admin.listingEdit.error.saveFailed": { km: "មិនអាចរក្សាទុក។", en: "Could not save." },
  "admin.listingEdit.saveChanges": { km: "រក្សាការផ្លាស់ប្តូរ", en: "Save changes" },

  // --- Admin: User form modal ---
  "admin.userForm.title.add": { km: "បន្ថែមអ្នកប្រើប្រាស់", en: "Add user" },
  "admin.userForm.title.edit": { km: "កែប្រែអ្នកប្រើប្រាស់", en: "Edit user" },
  "admin.userForm.field.name": { km: "ឈ្មោះ", en: "Name" },
  "admin.userForm.field.phone": { km: "លេខទូរស័ព្ទ", en: "Phone" },
  "admin.userForm.field.email": { km: "អ៊ីមែល (មិនចាំបាច់)", en: "Email (optional)" },
  "admin.userForm.field.avatarUrl": { km: "URL រូបភាព (មិនចាំបាច់)", en: "Avatar URL (optional)" },
  "admin.userForm.field.role": { km: "តួនាទី", en: "Role" },
  "admin.userForm.field.status": { km: "ស្ថានភាព", en: "Status" },
  "admin.userForm.error.required": { km: "ត្រូវការឈ្មោះ និងលេខទូរស័ព្ទ។", en: "Name and phone are required." },
  "admin.userForm.error.saveFailed": { km: "មិនអាចរក្សាទុក។", en: "Could not save." },
  "admin.userForm.submit.add": { km: "បន្ថែមអ្នកប្រើប្រាស់", en: "Add user" },
  "admin.userForm.submit.edit": { km: "រក្សាការផ្លាស់ប្តូរ", en: "Save changes" },

  // --- Admin: Users page ---
  "admin.users.title": { km: "អ្នកប្រើប្រាស់", en: "Users" },
  "admin.users.subtitle": { km: "មើល បន្ថែម កែប្រែ បិទ ឬលុបគណនីអ្នកប្រើប្រាស់។", en: "View, add, edit, disable or delete user accounts." },
  "admin.users.search.placeholder": { km: "ស្វែងរកឈ្មោះ លេខទូរស័ព្ទ ឬអ៊ីមែល", en: "Search name, phone, or email" },
  "admin.users.addUser": { km: "បន្ថែមអ្នកប្រើប្រាស់", en: "Add user" },
  "admin.users.empty": { km: "មិនមានអ្នកប្រើប្រាស់ត្រូវនឹងការស្វែងរកនេះ។", en: "No users match this search." },
  "admin.users.stat.users": { km: "អ្នកប្រើប្រាស់", en: "Users" },
  "admin.users.stat.active": { km: "សកម្ម", en: "Active" },
  "admin.users.stat.disabled": { km: "បានបិទ", en: "Disabled" },
  "admin.users.stat.admins": { km: "អ្នកគ្រប់គ្រង", en: "Admins" },
  "admin.users.stat.activeHint": { km: "{n} សកម្ម", en: "{n} active" },
  "admin.users.stat.noActive": { km: "មិនមានគណនីសកម្ម", en: "No active accounts" },
  "admin.users.stat.currentlyEnabled": { km: "បានបើកសព្វថ្ងៃ", en: "Currently enabled" },
  "admin.users.stat.allActive": { km: "គណនីទាំងអស់សកម្ម", en: "All accounts active" },
  "admin.users.stat.suspended": { km: "គណនីដែលត្រូវបានព្យួរ", en: "Suspended accounts" },
  "admin.users.stat.oneAdmin": { km: "១ គណនីអ្នកគ្រប់គ្រង", en: "1 admin account" },
  "admin.users.stat.manyAdmins": { km: "{n} គណនីអ្នកគ្រប់គ្រង", en: "{n} admin accounts" },
  "admin.users.col.user": { km: "អ្នកប្រើប្រាស់", en: "User" },
  "admin.users.col.phone": { km: "លេខទូរស័ព្ទ", en: "Phone" },
  "admin.users.col.role": { km: "តួនាទី", en: "Role" },
  "admin.users.col.status": { km: "ស្ថានភាព", en: "Status" },
  "admin.users.col.listings": { km: "បញ្ជី", en: "Listings" },
  "admin.users.col.actions": { km: "សកម្មភាព", en: "Actions" },
  "admin.users.action.viewProfile": { km: "មើលប្រវត្តិរូប", en: "View profile" },
  "admin.users.action.sendNotification": { km: "ផ្ញើការជូនដំណឹង", en: "Send notification" },
  "admin.users.action.edit": { km: "កែប្រែ", en: "Edit" },
  "admin.users.action.disable": { km: "បិទ", en: "Disable" },
  "admin.users.action.enable": { km: "បើក", en: "Enable" },
  "admin.users.action.delete": { km: "លុប", en: "Delete" },
  "admin.users.delete.title": { km: "លុបអ្នកប្រើប្រាស់?", en: "Delete user?" },
  "admin.users.delete.body.prefix": { km: "នេះនឹងលុប ", en: "This removes " },
  "admin.users.delete.body.suffix": { km: " ចេញពីបញ្ជីអ្នកគ្រប់គ្រង។ បញ្ជីរបស់ពួកគេនៅដដែលប៉ុន្តែនឹងគ្មានម្ចាស់។ មិនអាចសង្គ្រោះបានក្នុងទិន្នន័យសាកល្បង។", en: " from the admin user list. Their listings stay in place but become unowned. This can't be undone in the mock data." },
  "admin.users.listingsCount": { km: "{n} បញ្ជី", en: "{n} listings" },

  // --- Admin: User detail page ---
  "admin.userDetail.notFound.title": { km: "មិនឃើញអ្នកប្រើប្រាស់", en: "User not found" },
  "admin.userDetail.notFound.body": { km: "គណនីនេះប្រហែលជាត្រូវបានលុបហើយ។ ត្រឡប់ទៅបញ្ជីអ្នកប្រើដើម្បីគ្រប់គ្រងគណនីផ្សេងៗ។", en: "This account may have been deleted. Return to the user list to manage everyone else." },
  "admin.userDetail.backToUsers": { km: "ត្រឡប់ទៅអ្នកប្រើប្រាស់", en: "Back to users" },
  "admin.userDetail.allUsers": { km: "អ្នកប្រើប្រាស់ទាំងអស់", en: "All users" },
  "admin.userDetail.sendNotification": { km: "ផ្ញើការជូនដំណឹង", en: "Send notification" },
  "admin.userDetail.send": { km: "ផ្ញើ", en: "Send" },
  "admin.userDetail.edit": { km: "កែប្រែ", en: "Edit" },
  "admin.userDetail.disable": { km: "បិទ", en: "Disable" },
  "admin.userDetail.enable": { km: "បើក", en: "Enable" },
  "admin.userDetail.delete": { km: "លុប", en: "Delete" },
  "admin.userDetail.listings": { km: "បញ្ជី", en: "Listings" },
  "admin.userDetail.noListings.title": { km: "មិនទាន់មានបញ្ជី", en: "No listings yet" },
  "admin.userDetail.noListings.body": { km: "អ្នកប្រើប្រាស់នេះមិនទាន់បានផ្សាយបន្ទប់ណាមួយ។", en: "This user hasn't published any rooms." },
  "admin.userDetail.delete.title": { km: "លុបអ្នកប្រើប្រាស់នេះ?", en: "Delete this user?" },
  "admin.userDetail.delete.body.suffix": { km: " នឹងត្រូវលុបចេញពីបញ្ជីអ្នកប្រើប្រាស់។ បញ្ជីរបស់ពួកគេនៅដដែលប៉ុន្តែបាត់បង់តំណម្ចាស់។", en: " will be removed from the user directory. Their listings stay but lose their owner link." },
  "admin.userDetail.month": { km: "/ ខែ", en: "/ month" },

  // --- Admin: Settings page ---
  "admin.settings.title": { km: "ការកំណត់", en: "Settings" },
  "admin.settings.subtitle": { km: "គ្រប់គ្រងការកំណត់រួមនៃវេទិកា។ តម្លៃរក្សាទុកមូលដ្ឋាន — ការតភ្ជាប់ backend នឹងមកក្រោយ។", en: "Manage platform-wide configuration. Values persist locally — backend wiring comes later." },
  "admin.settings.general.title": { km: "ទូទៅ", en: "General" },
  "admin.settings.general.desc": { km: "អត្តសញ្ញាណគេហទំព័រ និងព័ត៌មានទាក់ទងដែលបង្ហាញនៅទូទាំង Joul។", en: "Site identity and contact details shown across Joul." },
  "admin.settings.field.siteName": { km: "ឈ្មោះគេហទំព័រ", en: "Site name" },
  "admin.settings.field.supportEmail": { km: "អ៊ីមែលជំនួយ", en: "Support email" },
  "admin.settings.field.supportPhone": { km: "លេខទូរស័ព្ទជំនួយ", en: "Support phone" },
  "admin.settings.field.defaultCurrency": { km: "រូបិយប័ណ្ណលំនាំដើម", en: "Default currency" },
  "admin.settings.taxonomy.title": { km: "ប្រភេទនៃបញ្ជី", en: "Listing taxonomy" },
  "admin.settings.taxonomy.desc": { km: "ប្រភេទកន្លែង និងសេវាកម្មដែលអ្នកជួលអាចត្រងបាន។ បញ្ជីថ្មីៗឃើញតែជម្រើសដែលបានបើកនៅទីនេះប៉ុណ្ណោះ។", en: "Property types and amenities renters can filter by. New listings only see options enabled here." },
  "admin.settings.propertyTypes": { km: "ប្រភេទកន្លែង", en: "Property types" },
  "admin.settings.propertyTypes.required": { km: "ត្រូវបើកប្រភេទកន្លែងយ៉ាងតិចមួយ។", en: "At least one property type must be enabled." },
  "admin.settings.amenities": { km: "សេវាកម្ម", en: "Amenities" },
  "admin.settings.amenities.placeholder": { km: "បន្ថែមសេវាកម្ម (ឧ. ដំបូល)", en: "Add an amenity (e.g. Rooftop)" },
  "admin.settings.amenities.empty": { km: "មិនទាន់មានសេវាកម្ម។", en: "No amenities yet." },
  "admin.settings.amenities.removeAria": { km: "ដក {name}", en: "Remove {name}" },
  "admin.settings.pricing.title": { km: "តម្លៃលំនាំដើម", en: "Pricing defaults" },
  "admin.settings.pricing.desc": { km: "បំពេញទម្រង់ផ្សាយបន្ទប់ជាមុនដើម្បីកុំឱ្យម្ចាស់ផ្ទះវាយលេខដដែលៗ។", en: "Pre-fill the list-room form so hosts don't enter the same numbers every time." },
  "admin.settings.pricing.defaultPeriod": { km: "ខួបតម្លៃលំនាំដើម", en: "Default price period" },
  "admin.settings.pricing.exchangeRate": { km: "អត្រាប្តូរប្រាក់ (រៀលក្នុង១ដុល្លារ)", en: "Exchange rate (KHR per USD)" },
  "admin.settings.pricing.water": { km: "ទឹកលំនាំដើម ($ / ម៉ែត្រគូប)", en: "Water default ($ / m³)" },
  "admin.settings.pricing.electricity": { km: "អគ្គិសនីលំនាំដើម ($ / kWh)", en: "Electricity default ($ / kWh)" },
  "admin.settings.pricing.wifi": { km: "វ៉ាយហ្វាយលំនាំដើម ($ / ខែ)", en: "Wi-Fi default ($ / month)" },
  "admin.settings.moderation.title": { km: "ការត្រួតពិនិត្យ", en: "Moderation" },
  "admin.settings.moderation.desc": { km: "តម្លៃលំនាំដើមសម្រាប់របៀបដែលបញ្ជី និងគណនីថ្មីៗត្រូវបានដោះស្រាយ។", en: "Defaults for how new listings and accounts are handled." },
  "admin.settings.moderation.autoPublish": { km: "ផ្សាយបញ្ជីថ្មីដោយស្វ័យប្រវត្តិ", en: "Auto-publish new listings" },
  "admin.settings.moderation.autoPublish.hint": { km: "បិទ = បញ្ជីត្រូវការការអនុម័តពីអ្នកគ្រប់គ្រងមុនពេលចេញផ្សាយ។", en: "Off = listings need admin approval before going live." },
  "admin.settings.moderation.phoneVerification": { km: "ត្រូវការការផ្ទៀងផ្ទាត់លេខទូរស័ព្ទ", en: "Require phone verification" },
  "admin.settings.moderation.phoneVerification.hint": { km: "អ្នកជួលត្រូវផ្ទៀងផ្ទាត់តាម SMS មុនពេលទាក់ទងម្ចាស់ផ្ទះ។", en: "Renters must verify by SMS before contacting hosts." },
  "admin.settings.moderation.emailAlerts": { km: "ផ្ញើការជូនដំណឹងតាមអ៊ីមែលសម្រាប់របាយការណ៍", en: "Send email alerts for reports" },
  "admin.settings.moderation.emailAlerts.hint": { km: "ជូនដំណឹងអ្នកគ្រប់គ្រងតាមអ៊ីមែលនៅពេលដែលបញ្ជីត្រូវបានរាយការណ៍។", en: "Notify admins by email when a listing is flagged." },
  "admin.settings.autoOccupy.label": {
    km: "បិទបញ្ជីដោយស្វ័យប្រវត្តិបន្ទាប់ពីគ្មានសកម្មភាពរយៈពេល (ថ្ងៃ)",
    en: "Auto-occupy listings after this many days of inactivity"
  },
  "admin.settings.autoOccupy.hint": {
    km: "បញ្ជីដែលអាចជួលបាន ប៉ុន្តែគ្មានការកែប្រែ ឬប្ដូរស្ថានភាពក្នុងរយៈពេលនេះ នឹងត្រូវបិទដោយស្វ័យប្រវត្តិ។ យ៉ាងតិច ៧ ថ្ងៃ។",
    en: "Available listings with no edits or status changes within this period are automatically marked Occupied. Minimum 7 days."
  },
  "admin.settings.access.title": { km: "ការគ្រប់គ្រងសិទ្ធិចូលប្រើ", en: "Access control" },
  "admin.settings.access.desc": { km: "អ្នកណាដែលអាចចូលដល់ផ្ទាំងអ្នកគ្រប់គ្រង។ បញ្ជីអនុញ្ញាតដំបូងដំណើរការទោះបីបញ្ជីអ្នកប្រើប្រាស់ទទេក៏ដោយ។", en: "Who can reach the admin console. The bootstrap allowlist works even if the user directory is empty." },
  "admin.settings.access.currentAdmins": { km: "អ្នកគ្រប់គ្រងបច្ចុប្បន្ន", en: "Current admins" },
  "admin.settings.access.noAdmins": { km: "មិនទាន់មានអ្នកគ្រប់គ្រងណាមួយត្រូវបានកំណត់។ បន្ថែម uid យ៉ាងតិចមួយខាងក្រោមមុនពេលចេញ។", en: "No admins configured. Add at least one uid below before logging out." },
  "admin.settings.access.allowlist": { km: "បញ្ជីអនុញ្ញាត", en: "Allowlist" },
  "admin.settings.access.role": { km: "តួនាទី", en: "Role" },
  "admin.settings.access.cantRemoveSelf": { km: "អ្នកមិនអាចលុបខ្លួនឯងបានទេ", en: "You can't remove yourself" },
  "admin.settings.access.removeFromAllowlist": { km: "ដកចេញពីបញ្ជីអនុញ្ញាត", en: "Remove from allowlist" },
  "admin.settings.access.addLabel": { km: "បន្ថែមទៅបញ្ជីអនុញ្ញាតដំបូង", en: "Add to bootstrap allowlist" },
  "admin.settings.access.addPlaceholder": { km: "uid អ្នកប្រើប្រាស់ (ឧ. demo-85512000000)", en: "user uid (e.g. demo-85512000000)" },
  "admin.settings.access.helperPrefix": { km: "សម្រាប់អ្នកគ្រប់គ្រងដែលមិននៅក្នុងបញ្ជីអនុញ្ញាត សូមកែប្រែអ្នកប្រើប្រាស់នៅក្នុង", en: "For non-allowlist admins, edit a user in" },
  "admin.settings.access.helperLink": { km: "អ្នកប្រើប្រាស់", en: "Users" },
  "admin.settings.access.helperSuffix": { km: " ហើយកំណត់តួនាទីរបស់ពួកគេទៅជា Admin។", en: " and set their role to Admin." },
  "admin.settings.danger.title": { km: "តំបន់គ្រោះថ្នាក់", en: "Danger zone" },
  "admin.settings.danger.desc": { km: "កំណត់ទិន្នន័យសាកល្បងមូលដ្ឋានឡើងវិញ។ មានប្រយោជន៍នៅពេលអ្នកប្តូរទិន្នន័យដំបូង ឬចង់ចាប់ផ្តើមឡើងវិញ។", en: "Reset all locally-seeded demo data. Useful when you change seeds or want a clean slate." },
  "admin.settings.danger.resetDone": { km: "ទិន្នន័យមូលដ្ឋានត្រូវបានកំណត់ឡើងវិញ។ ផ្ទុកទំព័រឡើងវិញដើម្បីបង្កើតទិន្នន័យដំបូងម្តងទៀត។", en: "Local data has been reset. Reload the page to re-seed." },
  "admin.settings.danger.resetButton": { km: "កំណត់ទិន្នន័យមូលដ្ឋានឡើងវិញ", en: "Reset local data" },
  "admin.settings.confirmReset.title": { km: "កំណត់ទិន្នន័យមូលដ្ឋានទាំងអស់ឡើងវិញ?", en: "Reset all local data?" },
  "admin.settings.confirmReset.body": { km: "នេះនឹងលុបអ្នកប្រើប្រាស់សាកល្បង ការជូនដំណឹងសាកល្បង ការកំណត់ និងបញ្ជីដែលរក្សាទុកមូលដ្ឋានទាំងអស់។ វគ្គចូលរបស់អ្នកនៅដដែល។ ទិន្នន័យនឹងបង្កើតឡើងវិញនៅពេលផ្ទុកលើកក្រោយ។", en: "This clears mock users, mock notifications, settings, and all locally-stored listings. Your sign-in session stays. The data will re-seed on next load." },
  "admin.settings.savedBar.saved": { km: "បានរក្សាទុក", en: "Saved" },
  "admin.settings.savedBar.unsaved": { km: "អ្នកមានការផ្លាស់ប្តូរដែលមិនទាន់រក្សាទុក។", en: "You have unsaved changes." },
  "admin.settings.savedBar.discard": { km: "បោះបង់", en: "Discard" },
  "admin.settings.savedBar.save": { km: "រក្សាការផ្លាស់ប្តូរ", en: "Save changes" },
  "admin.propertyType.room": { km: "បន្ទប់", en: "Room" },
  "admin.propertyType.apartment": { km: "អាផាតមិន", en: "Apartment" },
  "admin.propertyType.condo": { km: "ខុនដូ", en: "Condo" },
  "admin.propertyType.flat": { km: "ផ្ទះល្វែង", en: "Flat" },
  "admin.propertyType.house": { km: "ផ្ទះ", en: "House" },
  "admin.propertyType.villa": { km: "វីឡា", en: "Villa" },
  "admin.pricePeriod.daily": { km: "ប្រចាំថ្ងៃ", en: "Daily" },
  "admin.pricePeriod.weekly": { km: "ប្រចាំសប្តាហ៍", en: "Weekly" },
  "admin.pricePeriod.monthly": { km: "ប្រចាំខែ", en: "Monthly" },
  "admin.pricePeriod.yearly": { km: "ប្រចាំឆ្នាំ", en: "Yearly" },

  // --- Admin: Notifications page ---
  "admin.notifications.title": { km: "សារ", en: "Messages" },
  "admin.notifications.subtitle": { km: "តាមដានសកម្មភាពលើវេទិកា និងផ្សាយសារទៅអ្នកប្រើប្រាស់របស់អ្នក។", en: "Track platform activity and broadcast messages to your users." },
  "admin.notifications.markAllRead": { km: "សម្គាល់ទាំងអស់ថាបានអាន", en: "Mark all read" },
  "admin.notifications.viewAria": { km: "ទិដ្ឋភាពនៃការជូនដំណឹង", en: "Notifications view" },
  "admin.notifications.tab.incoming": { km: "ចូលមក", en: "Incoming" },
  "admin.notifications.tab.send": { km: "ផ្ញើ", en: "Send" },
  "admin.notifications.incoming.title": { km: "ការជូនដំណឹង", en: "Notifications" },
  "admin.notifications.incoming.subtitle": { km: "សកម្មភាពថ្មីពីអ្នកប្រើប្រាស់ និងបញ្ជីបន្ទប់។", en: "Activity from users and listings." },
  "admin.notifications.filter.all": { km: "ទាំងអស់", en: "All" },
  "admin.notifications.filter.listing": { km: "បញ្ជីថ្មី", en: "New Listing" },
  "admin.notifications.filter.register": { km: "ចុះឈ្មោះថ្មី", en: "New Register" },
  "admin.notifications.filter.read": { km: "បានអានតែប៉ុណ្ណោះ", en: "Read Only" },
  "admin.notifications.filter.unread": { km: "មិនទាន់អានតែប៉ុណ្ណោះ", en: "Unread Only" },
  "admin.notifications.incoming.empty.title": { km: "មិនមានសកម្មភាព", en: "All quiet" },
  "admin.notifications.incoming.empty.body": { km: "សកម្មភាពថ្មីពីអ្នកប្រើប្រាស់ និងបញ្ជីនឹងបង្ហាញនៅទីនេះ។", en: "New activity from users and listings will show up here." },
  "admin.notifications.row.unreadAria": { km: "មិនទាន់អាន", en: "Unread" },
  "admin.notifications.row.open": { km: "បើក ↗", en: "Open ↗" },
  "admin.notifications.row.markRead": { km: "សម្គាល់ថាបានអាន", en: "Mark as read" },
  "admin.notifications.row.delete": { km: "លុបការជូនដំណឹង", en: "Delete notification" },
  "admin.notifications.row.deleteTitle": { km: "លុប", en: "Delete" },
  "admin.notifications.send.savedTemplate": { km: "រក្សាទុក \"{name}\"។", en: "Saved \"{name}\"." },
  "admin.notifications.send.sentTo": { km: "បានផ្ញើទៅ {summary}។", en: "Sent to {summary}." },
  "admin.notifications.send.dismiss": { km: "បិទ", en: "Dismiss" },
  "admin.notifications.compose.title": { km: "តែងការជូនដំណឹង", en: "Compose notification" },
  "admin.notifications.compose.placeholders": { km: "កន្លែងជំនួស៖", en: "Placeholders:" },
  "admin.notifications.compose.template.blank": { km: "ទទេ", en: "Blank" },
  "admin.notifications.compose.field.title": { km: "ចំណងជើង", en: "Title" },
  "admin.notifications.compose.field.title.placeholder": { km: "ឧ. បន្ទប់ថ្មីនៅ BKK1", en: "e.g. New rooms in BKK1" },
  "admin.notifications.compose.field.message": { km: "សារ", en: "Message" },
  "admin.notifications.compose.field.message.placeholder": { km: "សរសេរសារដែលអ្នកប្រើប្រាស់របស់អ្នកនឹងទទួល…", en: "Write the message your users will receive…" },
  "admin.notifications.compose.preview.as": { km: "មើលជាមុនជា {name}", en: "Preview as {name}" },
  "admin.notifications.compose.preview.noTitle": { km: "(មិនមានចំណងជើង)", en: "(no title)" },
  "admin.notifications.compose.preview.noMessage": { km: "(មិនមានសារ)", en: "(no message)" },
  "admin.notifications.compose.saveTemplate": { km: "រក្សាទុកជាគំរូ", en: "Save as template" },
  "admin.notifications.compose.updateTemplate": { km: "ធ្វើបច្ចុប្បន្នភាពគំរូ", en: "Update template" },
  "admin.notifications.compose.send.one": { km: "ផ្ញើទៅ {n} អ្នកប្រើ", en: "Send to {n} user" },
  "admin.notifications.compose.send.many": { km: "ផ្ញើទៅ {n} អ្នកប្រើ", en: "Send to {n} users" },
  "admin.notifications.history.title": { km: "ប្រវត្តិការផ្ញើ", en: "Sent history" },
  "admin.notifications.history.empty": { km: "មិនទាន់បានផ្ញើអ្វី", en: "Nothing sent yet" },
  "admin.notifications.history.empty.body": { km: "នៅពេលអ្នកផ្ញើការជូនដំណឹង វានឹងត្រូវបានកត់ត្រានៅទីនេះ។", en: "When you send a notification, it will be logged here." },
  "admin.notifications.history.campaigns.one": { km: "{n} ការផ្សព្វផ្សាយ", en: "{n} campaign" },
  "admin.notifications.history.campaigns.many": { km: "{n} ការផ្សព្វផ្សាយ", en: "{n} campaigns" },
  "admin.notifications.history.deleteAria": { km: "លុបការផ្សព្វផ្សាយ", en: "Delete campaign" },
  "admin.notifications.history.deleteTitle": { km: "លុប", en: "Delete" },
  "admin.notifications.templates.title": { km: "គំរូ", en: "Templates" },
  "admin.notifications.templates.new": { km: "ថ្មី", en: "New" },
  "admin.notifications.templates.newAria": { km: "គំរូថ្មី", en: "New template" },
  "admin.notifications.templates.empty": { km: "រក្សាទុកគំរូដែលអាចប្រើឡើងវិញដើម្បីឱ្យសារទូទៅនៅជិតក្បែរ។", en: "Save reusable templates so common messages stay one click away." },
  "admin.notifications.templates.editAria": { km: "កែប្រែគំរូ", en: "Edit template" },
  "admin.notifications.templates.deleteAria": { km: "លុបគំរូ", en: "Delete template" },
  "admin.notifications.recipients.label": { km: "អ្នកទទួល", en: "Recipients" },
  "admin.notifications.recipients.count.one": { km: "{n} អ្នកប្រើ", en: "{n} user" },
  "admin.notifications.recipients.count.many": { km: "{n} អ្នកប្រើ", en: "{n} users" },
  "admin.notifications.audience.all": { km: "អ្នកប្រើទាំងអស់", en: "All users" },
  "admin.notifications.audience.byRole": { km: "តាមតួនាទី", en: "By role" },
  "admin.notifications.audience.specific": { km: "អ្នកប្រើជាក់លាក់", en: "Specific users" },
  "admin.notifications.audience.users": { km: "អ្នកប្រើ", en: "Users" },
  "admin.notifications.audience.admins": { km: "អ្នកគ្រប់គ្រង", en: "Admins" },
  "admin.notifications.picker.placeholder": { km: "ជ្រើសរើសអ្នកប្រើ…", en: "Pick users…" },
  "admin.notifications.picker.search": { km: "ស្វែងរកឈ្មោះ លេខទូរស័ព្ទ ឬអ៊ីមែល", en: "Search name, phone, or email" },
  "admin.notifications.picker.noMatches": { km: "មិនមានលទ្ធផល។", en: "No matches." },
  "admin.notifications.picker.removeAria": { km: "ដក {name}", en: "Remove {name}" },
  "admin.notifications.template.create.title": { km: "រក្សាទុកគំរូ", en: "Save template" },
  "admin.notifications.template.edit.title": { km: "កែប្រែគំរូ", en: "Edit template" },
  "admin.notifications.template.field.name": { km: "ឈ្មោះគំរូ", en: "Template name" },
  "admin.notifications.template.field.name.placeholder": { km: "ឧ. បញ្ជីត្រូវបានអនុម័ត", en: "e.g. Listing approved" },
  "admin.notifications.template.field.title": { km: "ចំណងជើង", en: "Title" },
  "admin.notifications.template.field.message": { km: "សារ", en: "Message" },
  "admin.notifications.template.save": { km: "រក្សាទុកគំរូ", en: "Save template" },
  "admin.notifications.template.saveChanges": { km: "រក្សាការផ្លាស់ប្តូរ", en: "Save changes" },
  "admin.notifications.template.delete.title": { km: "លុបគំរូ?", en: "Delete template?" },
  "admin.notifications.template.delete.body.prefix": { km: "នេះនឹងលុប ", en: "This removes " },
  "admin.notifications.template.delete.body.suffix": { km: " ចេញពីគំរូដែលបានរក្សាទុករបស់អ្នក។", en: " from your saved templates." },
  "admin.notifications.campaign.delete.title": { km: "លុបការផ្សព្វផ្សាយ?", en: "Delete campaign?" },
  "admin.notifications.campaign.delete.body.prefix": { km: "លុប ", en: "Remove " },
  "admin.notifications.campaign.delete.body.suffix": { km: " ចេញពីប្រវត្តិការផ្ញើរបស់អ្នក?", en: " from your sent history?" },
  "admin.notifications.time.justNow": { km: "ឥឡូវនេះ", en: "just now" },
  "admin.notifications.time.minutesAgo": { km: "{n} នាទីមុន", en: "{n}m ago" },
  "admin.notifications.time.hoursAgo": { km: "{n} ម៉ោងមុន", en: "{n}h ago" },
  "admin.notifications.time.daysAgo": { km: "{n} ថ្ងៃមុន", en: "{n}d ago" },

  // --- Admin: toast messages ---
  "toast.admin.listingUpdated": { km: "បញ្ជីត្រូវបានធ្វើបច្ចុប្បន្នភាព។", en: "Listing updated." },
  "toast.admin.listing.occupied": { km: "\"{title}\" សម្គាល់ថាមានអ្នកជួល។", en: "\"{title}\" marked as occupied." },
  "toast.admin.listing.available": { km: "\"{title}\" អាចជួលបានឥឡូវនេះ។", en: "\"{title}\" is now available." },
  "toast.admin.listing.deleted": { km: "\"{title}\" បានលុប។", en: "\"{title}\" deleted." },
  "toast.admin.user.added": { km: "អ្នកប្រើប្រាស់ \"{name}\" ត្រូវបានបន្ថែម។", en: "User \"{name}\" added." },
  "toast.admin.user.updated": { km: "អ្នកប្រើប្រាស់ \"{name}\" ត្រូវបានធ្វើបច្ចុប្បន្នភាព។", en: "User \"{name}\" updated." },
  "toast.admin.user.deleted": { km: "អ្នកប្រើប្រាស់ \"{name}\" បានលុប។", en: "User \"{name}\" deleted." },
  "toast.admin.user.disabled": { km: "\"{name}\" ត្រូវបានបិទ។", en: "\"{name}\" disabled." },
  "toast.admin.user.enabled": { km: "\"{name}\" ត្រូវបានបើកឡើងវិញ។", en: "\"{name}\" re-enabled." },
  "toast.admin.user.listingsHidden": { km: "បញ្ជី {n} ត្រូវបានសម្គាល់ថាមានអ្នកជួល។", en: "{n} listing(s) marked as occupied." },
  "toast.admin.settings.saved": { km: "ការកំណត់ត្រូវបានរក្សាទុក។", en: "Settings saved." },
  "toast.admin.settings.reset": { km: "ទិន្នន័យមូលដ្ឋានត្រូវបានកំណត់ឡើងវិញ។", en: "Local data reset." },
  "toast.admin.send.one": { km: "បានផ្ញើទៅអ្នកទទួល ១ នាក់។", en: "Sent to 1 recipient." },
  "toast.admin.send.many": { km: "បានផ្ញើទៅអ្នកទទួល {n} នាក់។", en: "Sent to {n} recipients." },

  // Date range picker
  "dateRange.aria": { km: "ជ្រើសរើសជួរកាលបរិច្ឆេទ", en: "Select date range" },
  "dateRange.year": { km: "ឆ្នាំ", en: "Year" },
  "dateRange.prevYear": { km: "ឆ្នាំមុន", en: "Previous year" },
  "dateRange.nextYear": { km: "ឆ្នាំបន្ទាប់", en: "Next year" },
  "dateRange.prevMonth": { km: "ខែមុន", en: "Previous month" },
  "dateRange.nextMonth": { km: "ខែបន្ទាប់", en: "Next month" },
  "dateRange.start": { km: "ចាប់ផ្តើម", en: "Start" },
  "dateRange.end": { km: "បញ្ចប់", en: "End" },
  "dateRange.saveFilters": { km: "រក្សាទុកតម្រង", en: "Save filters" },
  "dateRange.apply": { km: "អនុវត្ត", en: "Apply" },
  "dateRange.preset.today": { km: "ថ្ងៃនេះ", en: "Today" },
  "dateRange.preset.yesterday": { km: "ម្សិលមិញ", en: "Yesterday" },
  "dateRange.preset.thisWeek": { km: "សប្តាហ៍នេះ", en: "This Week" },
  "dateRange.preset.lastWeek": { km: "សប្តាហ៍មុន", en: "Last Week" },
  "dateRange.preset.thisMonth": { km: "ខែនេះ", en: "This Month" },
  "dateRange.preset.lastMonth": { km: "ខែមុន", en: "Last Month" },
  "dateRange.preset.thisYear": { km: "ឆ្នាំនេះ", en: "This Year" },
  "dateRange.month.0": { km: "មករា", en: "January" },
  "dateRange.month.1": { km: "កុម្ភៈ", en: "February" },
  "dateRange.month.2": { km: "មីនា", en: "March" },
  "dateRange.month.3": { km: "មេសា", en: "April" },
  "dateRange.month.4": { km: "ឧសភា", en: "May" },
  "dateRange.month.5": { km: "មិថុនា", en: "June" },
  "dateRange.month.6": { km: "កក្កដា", en: "July" },
  "dateRange.month.7": { km: "សីហា", en: "August" },
  "dateRange.month.8": { km: "កញ្ញា", en: "September" },
  "dateRange.month.9": { km: "តុលា", en: "October" },
  "dateRange.month.10": { km: "វិច្ឆិកា", en: "November" },
  "dateRange.month.11": { km: "ធ្នូ", en: "December" },
  "dateRange.month.short.0": { km: "ម.ក", en: "Jan" },
  "dateRange.month.short.1": { km: "កុ", en: "Feb" },
  "dateRange.month.short.2": { km: "មិ", en: "Mar" },
  "dateRange.month.short.3": { km: "មេ", en: "Apr" },
  "dateRange.month.short.4": { km: "ឧ", en: "May" },
  "dateRange.month.short.5": { km: "មិ.ថ", en: "Jun" },
  "dateRange.month.short.6": { km: "ក.ក", en: "Jul" },
  "dateRange.month.short.7": { km: "សី", en: "Aug" },
  "dateRange.month.short.8": { km: "ក.ញ", en: "Sep" },
  "dateRange.month.short.9": { km: "តុ", en: "Oct" },
  "dateRange.month.short.10": { km: "វិ", en: "Nov" },
  "dateRange.month.short.11": { km: "ធ្នូ", en: "Dec" },
  "dateRange.weekday.sun": { km: "អា", en: "Sun" },
  "dateRange.weekday.mon": { km: "ច", en: "Mon" },
  "dateRange.weekday.tue": { km: "អ", en: "Tue" },
  "dateRange.weekday.wed": { km: "ព", en: "Wed" },
  "dateRange.weekday.thu": { km: "ព្រ", en: "Thu" },
  "dateRange.weekday.fri": { km: "សុ", en: "Fri" },
  "dateRange.weekday.sat": { km: "ស", en: "Sat" },
  "dateRange.allDates": { km: "កាលបរិច្ឆេទទាំងអស់", en: "All dates" },

  // Price range picker
  "priceRange.aria": { km: "ជ្រើសរើសជួរតម្លៃ", en: "Select price range" },
  "priceRange.heading": { km: "ជួរតម្លៃ", en: "Price range" },
  "priceRange.hint": { km: "ទុកចន្លោះទទេសម្រាប់គ្មានកំណត់។", en: "Leave a field empty for no limit." },
  "priceRange.min": { km: "អប្បបរមា", en: "Min" },
  "priceRange.max": { km: "អតិបរមា", en: "Max" },
  "priceRange.apply": { km: "អនុវត្ត", en: "Apply" },

  // Location picker
  "locationPicker.aria": { km: "ទីតាំង", en: "Location" },
  "locationPicker.title": { km: "ទីតាំង", en: "Location" },
  "locationPicker.back.aria": { km: "ត្រឡប់ក្រោយ", en: "Back" },
  "locationPicker.allLabel.select": { km: "សម្អាត", en: "Clear" },
  "locationPicker.allLabel.browse": { km: "បង្ហាញបន្ទប់ទាំងអស់", en: "Show all rooms" },
  "locationPicker.use": { km: "ប្រើ {name}", en: "Use {name}" },
  "locationPicker.showAllIn": { km: "បង្ហាញបន្ទប់ទាំងអស់នៅ {name}", en: "Show all rooms in {name}" },

  // Map pin picker
  "mapPin.aria": { km: "ដាក់ចំណុចលើផែនទី", en: "Pin location on map" },
  "mapPin.title": { km: "ដាក់ចំណុច", en: "Pin location" },
  "mapPin.useMyLocation.aria": { km: "ប្រើទីតាំងរបស់ខ្ញុំ", en: "Use my location" },

  // Image gallery
  "gallery.prev.aria": { km: "រូបភាពមុន", en: "Previous photo" },
  "gallery.next.aria": { km: "រូបភាពបន្ទាប់", en: "Next photo" },
  "gallery.photoCount": { km: "{n} រូបភាព", en: "{n} photos" },
  "gallery.showPhoto.aria": { km: "បង្ហាញរូបភាព {n}", en: "Show photo {n}" },
  "gallery.allPhotos.aria": { km: "{title} — រូបភាពទាំងអស់", en: "{title} — all photos" },

  // Toaster
  "toast.dismiss.aria": { km: "បិទ", en: "Dismiss" },

  // Error boundary
  "errorBoundary.title": { km: "មានបញ្ហាមួយបានកើតឡើង", en: "Something went wrong" },
  "errorBoundary.body": { km: "យើងជួបបញ្ហាមិនបានរំពឹងទុកក្នុងការបង្ហាញផ្នែកនេះ។ ព្យាយាមម្តងទៀត — ប្រសិនបើនៅតែកើតមាន សូមផ្ទុកទំព័រឡើងវិញ។", en: "We hit an unexpected error rendering this section. Try again — if it keeps happening, refresh the page." },

  // Contact list editor
  "contactList.remove.aria": { km: "ដក {label} {n}", en: "Remove {label} {n}" },

  // Explore empty states / map errors
  "explore.empty.map.title": { km: "មិនមានបន្ទប់នៅក្នុងតំបន់នេះទេ", en: "No rooms in this area" },
  "explore.empty.filters.title": { km: "មិនមានបន្ទប់ត្រូវនឹងការស្វែងរកនេះទេ", en: "No rooms match these filters" },
  "explore.empty.map.hint": { km: "អូស ឬពង្រីកដើម្បីស្វែងរកបន្ទប់បន្ថែម។", en: "Pan or zoom out to find more rooms." },
  "explore.empty.filters.hint": { km: "សាកល្បងពង្រីកទីតាំង ឬជម្រះប្រភេទកន្លែង។", en: "Try widening the location or clearing the property type." },
  "explore.map.loadFailed": { km: "ផែនទីបរាជ័យក្នុងការផ្ទុក។ ប្តូរទៅទិដ្ឋភាពបញ្ជីបន្តស្វែងរក។", en: "Map failed to load. Switch to list view to keep browsing." }
};

/**
 * Minimal language preference hook.
 *
 * - Defaults to "km" (Khmer) because the audience is Cambodian.
 * - Persists the choice in localStorage so it survives reloads.
 * - Starts with "km" on both server and client to avoid React hydration
 *   mismatches; the stored value is synced in an effect on mount.
 */
export function useLanguage() {
  const [language, setLanguageState] = useState<Language>("km");

  useLayoutEffect(() => {
    // Fires synchronously before the browser's first paint — the language
    // correction happens invisibly so the user never sees a Khmer flash.
    setLanguageState(readStored());
    const sync = () => setLanguageState(readStored());
    window.addEventListener(EVENT, sync);
    const onStorage = (e: StorageEvent) => {
      if (e.key === STORAGE_KEY) sync();
    };
    window.addEventListener("storage", onStorage);
    return () => {
      window.removeEventListener(EVENT, sync);
      window.removeEventListener("storage", onStorage);
    };
  }, []);

  const toggleLanguage = useCallback(() => {
    const next: Language = readStored() === "km" ? "en" : "km";
    try {
      window.localStorage.setItem(STORAGE_KEY, next);
    } catch {
      // localStorage may be unavailable (private mode, etc.) — non-fatal.
    }
    window.dispatchEvent(new Event(EVENT));
  }, []);

  return { language, toggleLanguage };
}

/**
 * Translator hook. Returns a `t(key, vars?)` function that looks up the
 * current language's string. Unknown keys fall through to the key itself so
 * missing translations are visible.
 */
export function useT() {
  const { language } = useLanguage();
  return useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      const entry = DICT[key];
      let value = entry?.[language] ?? entry?.en ?? key;
      if (vars) {
        for (const [k, v] of Object.entries(vars)) {
          value = value.replace(`{${k}}`, String(v));
        }
      }
      return value;
    },
    [language]
  );
}
